apiVersion: v2
name: ffc-demo-payment-service-infra
description: A ASO Helm chart to deploy the FFC Demo Payment Service Infrastructure
version: 0.0.1
dependencies:
- name: adp-aso-helm-library
  version: 1.0.19-prerelease2
  repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-aso-helm-library

