namespace: ffc-demo

serviceBusResourceGroupName: sndadpinfrg1401
serviceBusNamespaceName: sndadpinfsb1401

asoAnnotations:
  serviceoperator.azure.com/reconcile-policy: manage

namespaceTopics:
  - name: schedule
    owner: "no"
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: payment
  - name: payment
    owner: "no"
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: payment
      
postgresResourceGroupName: sndadpdbsrg1401
postgresServerName: sndadpdbsps1401
postgres:
  db:
    name: payment 
    charset: UTF8
    collation: en_US.utf8

tags:
  Environment: SND1
  ServiceCode: ADP
  ServiceName: ffc-demo-payment-service
  ServiceType: Shared
  Purpose: Define purpose
  ManagedBy: ASO
  kubernetes_cluster: SNDADPINFAK1401

#Dummy placeholder values only for linting. NOT TO BE POPULATED
subscriptionId: "dummySubscriptionId"
userAssignedIdentity: {}
teamMIPrefix: "dummy-mi-prefix"
serviceName: "dummy-svc"
teamResourceGroupName: "dummy-rsg"