version: '3.4'
services:
  mine-support-payment-service:
    command: sh -c "scripts/wait-for/wait-for mine-support-payment-postgres:5432 -- scripts/wait-for/wait-for mine-support-message-queue:5672 -- npm run migrate && npm run start:watch"
    networks:
      - mine-support
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

networks:
  mine-support:
   external: true

volumes:
  node_modules:
