version: '3.4'
services:
  mine-support-payment-service:
    command: sh -c "scripts/wait-for/wait-for mine-support-payment-postgres:5432 -- scripts/wait-for/wait-for mine-support-payment-message-queue:8161 -- npm run migrate && npm run test"
    volumes:
      - ./test-output:/usr/src/app/test-output
