version: '3.4'
services:
  mine-support-payment-service:
    command: ./wait-for mine-support-payment-postgres:5432 -- ./wait-for amq:8161 -- ./migrate-test
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
      - ./test-output:/usr/src/app/test-output

volumes:
  node_modules:
