version: '3'
services:
  mine-support-payment-service:
    build: .
    image: mine-support-payment-service
    container_name: mine-support-payment-service
    command: npm run watch:server
    ports:
      - "3004:3004"
    volumes:
      - node_modules:/home/node/node_modules
      - .:/home/node

volumes:
  node_modules:
