version: '3.7'
services:
  ffc-demo-payment-service:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY:-562955126301.dkr.ecr.eu-west-2.amazonaws.com}
    image: ffc-demo-payment-service
    depends_on:
      - ffc-demo-payment-postgres
    environment:
      POSTGRES_DB: ffc_demo_payment_service
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-payment-postgres
      POSTGRES_PORT: 5432
      SCHEDULE_ENDPOINT: http://ffc-demo-payment-message-queue:9324
      SCHEDULE_QUEUE_URL: http://ffc-demo-payment-message-queue:9324/queue/schedule
      SCHEDULE_QUEUE_ACCESS_KEY_ID: elasticmq
      SCHEDULE_QUEUE_ACCESS_KEY: elasticmq
      PAYMENT_ENDPOINT: http://ffc-demo-payment-message-queue:9324
      PAYMENT_QUEUE_URL: http://ffc-demo-payment-message-queue:9324/queue/payment
      PAYMENT_QUEUE_ACCESS_KEY_ID: elasticmq
      PAYMENT_QUEUE_ACCESS_KEY: elasticmq
    volumes:
      - ./server/:/home/node/server/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payment_service
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-demo-payment-message-queue:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"

volumes:
  postgres_data: {}
