version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-payment-service:
    build:
      context: .
      target: development
    image: ffc-demo-payment-service
    command: sh -c "npm run start:watch"
    ports:
      - "3004:3004"

  ffc-demo-payment-postgres:
    ports:
      - "5432:5432"
