# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-payment-service:
    build:
      context: .
      target: development
    command: sh -c "npm run test"
    environment:
      PACT_BROKER_URL: ${PACT_BROKER_URL:-notset}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME:-notset}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD:-notset}
    depends_on:
      - kafka
      - zookeeper
      - ffc-demo-payment-postgres
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json

  ffc-demo-payment-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
