version: '3.7'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-payment-service:
    build:
      context: .
      target: development
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-payment-postgres:5432 --
        scripts/wait-for/wait-for ffc-demo-message-queue:9324 --
        npm run migrate &&
        npm run start:watch"
    ports:
      - "3004:3004"
    networks:
      - default
      - ffc-demo

networks:
  ffc-demo:
   external: true
