version: '3.4'
services:
  mine-support-payment-service:
    volumes: 
    - node_modules:/usr/src/app/node_modules
    - .:/usr/src/app
    - ./test-output:/usr/src/app/test-output
    command: ./wait-for mine-support-postgres-payments:5432 -- ./wait-for amq:8161 -- ./migrate-test

volumes:
  node_modules:
