version: '3'
services:
  mine-support-payment-service:
    build: .
    image: mine-support-payment-service
    container_name: mine-support-payment-service
    networks:
      - mine-support
    ports:
      - "3004:3004"

networks:
  mine-support:
    external: true
