version: '3.7'
services:
  ffc-demo-payment-service:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service
    depends_on:
      - ffc-demo-payment-postgres
      - ffc-demo-payment-message-queue  
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY:
      APPINSIGHTS_CLOUD_ROLE: payment-service-local
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-payment-postgres
      POSTGRES_PORT: 5432
      MESSAGE_QUEUE_HOST: ffc-demo-payment-message-queue
      MESSAGE_QUEUE_PORT: 5672
      MESSAGE_QUEUE_RECONNECT_LIMIT: 10
      SCHEDULE_QUEUE_ADDRESS: schedule
      SCHEDULE_QUEUE_USER: artemis
      SCHEDULE_QUEUE_PASSWORD: artemis
      PAYMENT_QUEUE_ADDRESS: payment
      PAYMENT_QUEUE_USER: artemis
      PAYMENT_QUEUE_PASSWORD: artemis
      OIDC_PROVIDER: dev
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}      
      B2C_CLIENT_ID: ${B2C_CLIENT_ID}
      B2C_CLIENT_SECRET: ${B2C_CLIENT_SECRET}
      B2C_URL: ${B2C_URL}      
    volumes:
      - ./server/:/home/node/server/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-demo-payment-message-queue:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis

volumes:
  postgres_data: {}
