version: '3.7'
services:
  ffc-demo-payment-service:
    build: .
    image: ffc-demo-payment-service
    depends_on:
      - ffc-demo-payment-postgres
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-payment-postgres
      POSTGRES_PORT: 5432
      MESSAGE_QUEUE_HOST: host.docker.internal
      MESSAGE_QUEUE_PORT: 5672
      MESSAGE_QUEUE_RECONNECT_LIMIT: 10
      SCHEDULE_QUEUE_ADDRESS: schedule
      SCHEDULE_QUEUE_USER: artemis
      SCHEDULE_QUEUE_PASSWORD: artemis
      PAYMENT_QUEUE_ADDRESS: payment
      PAYMENT_QUEUE_USER: artemis
      PAYMENT_QUEUE_PASSWORD: artemis
    volumes:
      - node_modules:/usr/src/app/node_modules/
      - .:/usr/src/app

  ffc-demo-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules: {}
  postgres_data: {}
