version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-payment-service:
    build:
      context: .
      target: development
    image: ffc-demo-payment-service
    command: sh -c "scripts/wait-for-dependencies && npm run start:watch"
    ports:
      - "3004:3004"
    depends_on:
      - ffc-demo-payment-message-queue

  ffc-demo-payment-message-queue:
    ports:
      - "8161:8161"
      - "5672:5672"

  ffc-demo-payment-postgres:
    ports:
      - "5432:5432"
