version: '3.7'
services:
  ffc-demo-payment-service:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service
    depends_on:
      - ffc-demo-payment-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-payment-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY:
      B2C_CLIENT_ID: ${B2C_CLIENT_ID}
      B2C_CLIENT_SECRET: ${B2C_CLIENT_SECRET}
      B2C_URL: ${B2C_URL}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      OIDC_PROVIDER: dev
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      PAYMENT_QUEUE_ADDRESS: ${PAYMENT_QUEUE_ADDRESS:-notset}
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-payment-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      SCHEDULE_QUEUE_ADDRESS: ${SCHEDULE_QUEUE_ADDRESS:-notset}
    volumes:
      - ./server/:/home/node/server/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
