version: '3.7'
services:
  ffc-demo-payment-service:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service
    container_name: ffc-demo-payment-service
    depends_on:
      - ffc-demo-payment-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-payment-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      B2C_CLIENT_ID: ${B2C_CLIENT_ID}
      B2C_CLIENT_SECRET: ${B2C_CLIENT_SECRET}
      B2C_URL: ${B2C_URL}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      OIDC_PROVIDER: dev
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-notset}
      PAYMENT_SUBSCRIPTION_ADDRESS: ${PAYMENT_SUBSCRIPTION_ADDRESS:-notset}
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-payment-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      SCHEDULE_SUBSCRIPTION_ADDRESS: ${SCHEDULE_SUBSCRIPTION_ADDRESS:-notset}
      SCHEDULE_TOPIC_ADDRESS: ${SCHEDULE_TOPIC_ADDRESS:-notset}
      EVENT_HOST: kafka
      EVENT_USERNAME: kafka
      EVENT_PASSWORD: kafka

  ffc-demo-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  zookeeper:
    image: bitnami/zookeeper
    tmpfs: "/datalog"

    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    
  kafka:
    image: bitnami/kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,CLIENT://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,CLIENT://kafka:9093,EXTERNAL://host.docker.internal:9094
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_USERS: kafka
      KAFKA_CLIENT_PASSWORDS: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
