version: '3.4'
services:
  mine-support-payment-service:
    volumes:
      - ./test-output:/usr/src/app/test-output
    command: ./wait-for mine-support-postgres-payments:5432 -- ./migrate-test
