version: '3'
services:
  mine-support-payment-service:
    environment:
      MINE_SUPPORT_MESSAGE_QUEUE: amqp://mine-support-message-queue
    networks:
      - mine-support

networks:
  mine-support:
    external: true
