apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        environment: {{ .Values.environment }}
      annotations:
        redeployOnChange: {{ .Values.container.redeployOnChange | quote }}
    spec:
      restartPolicy: {{ .Values.container.restartPolicy }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
        command:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
        args:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        securityContext:
          runAsUser: {{ .Values.container.runAsUser }}
          runAsNonRoot: {{ .Values.container.runAsNonRoot }}
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        env:
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: POSTGRES_USERNAME
          value: {{ .Values.postgresUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresDatabase }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgresHost }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgresPort | quote }}
        - name: MESSAGE_QUEUE_HOST
          value: {{ .Values.container.messageQueueHost }}
        - name: MESSAGE_QUEUE_PORT
          value: {{ .Values.container.messageQueuePort | quote}}
        - name: MESSAGE_QUEUE_TRANSPORT
          value: {{ .Values.container.messageQueueTransport }}
        - name: SCHEDULE_QUEUE_ADDRESS
          value: {{ .Values.container.scheduleQueueAddress }}
        - name: SCHEDULE_QUEUE_USER
          value: {{ .Values.container.scheduleQueueUser }}
        - name: SCHEDULE_QUEUE_PASSWORD
          value: {{ .Values.container.scheduleQueuePassword }}
        - name: PAYMENT_QUEUE_ADDRESS
          value: {{ .Values.container.paymentQueueAddress }}
        - name: PAYMENT_QUEUE_USER
          value: {{ .Values.container.paymentQueueUser }}
        - name: PAYMENT_QUEUE_PASSWORD
          value: {{ .Values.container.paymentQueuePassword }}
        - name: PORT
          value: "3004"
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          requests:
            memory: {{ .Values.container.requestMemory }}
            cpu: {{ .Values.container.requestCpu }}
          limits:
            memory: {{ .Values.container.limitMemory }}
            cpu: {{ .Values.container.limitCpu }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
