apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.name }}
    spec:
      containers:   
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        env:                
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: POSTGRES_USERNAME
          value: {{ .Values.postgresUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresDatabase }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgresHost }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgresPort | quote }}
        - name: MESSAGE_QUEUE_HOST
          value: {{ .Values.container.messageQueueHost }}
        - name: MESSAGE_QUEUE_PORT
          value: {{ .Values.container.messageQueuePort | quote}}
        - name: MESSAGE_QUEUE_TRANSPORT
          value: {{ .Values.container.messageQueueTransport }}
        - name: SCHEDULE_QUEUE_ADDRESS
          value: {{ .Values.container.scheduleQueueAddress }}
        - name: SCHEDULE_QUEUE_USER
          value: {{ .Values.container.scheduleQueueUser }}
        - name: SCHEDULE_QUEUE_PASSWORD
          value: {{ .Values.container.scheduleQueuePassword }}
        - name: PAYMENT_QUEUE_ADDRESS
          value: {{ .Values.container.paymentQueueAddress }}
        - name: PAYMENT_QUEUE_USER
          value: {{ .Values.container.paymentQueueUser }}
        - name: PAYMENT_QUEUE_PASSWORD
          value: {{ .Values.container.paymentQueuePassword }}
        - name: PORT
          value: "3004"
        ports:
        - containerPort: {{ .Values.container.port }}
        command: ["/bin/sh","-c"]
        args: ["sequelize db:migrate; node index"]
        resources:
          requests:
            memory: {{ .Values.container.requestMemory | quote }}
            cpu: {{ .Values.container.requestCpu | quote }}
          limits:
            memory: {{ .Values.container.limitMemory | quote }}
            cpu: {{ .Values.container.limitCpu | quote }}
        volumes:                      
      restartPolicy: {{ .Values.container.restartPolicy }}
status: {}
