apiVersion: v2
description: A Helm chart for Kubernetes
name: ffc-demo-payment-service
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.5.3
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
