name: ffc-demo-payment-service
namespace: ffc-demo
image: ffc-demo-payment-service

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5

container:
  port: 3004
  memCpuTier: M

readinessProbe:
  path: /healthy
  port: 3004
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true
