environment: development
postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_payments
# postgresHost is the host name of the PostgreSQL service
postgresHost: ffc-demo-payments-postgres
# postgresExternalName is the external host name to which PostgreSQL
# requests should be forwarded. If empty, PostgreSQL is assumed to be
# within the cluster and accessible via postgresHost
postgresExternalName:
postgresPort: 5432
name: ffc-demo-payment-service
image: ffc-demo-payment-service
imagePullSecret:
service:
  type: ClusterIP
  port: 80
container:
  port: 3004
  registry:
  tag: latest
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 40m
  limitMemory: 120Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  redeployOnChange: update this field to force a change
  restartPolicy: Always
  messageQueueHost: amq
  messageQueuePort: "5672"
  messageQueueReconnectLimit: 10
  messageQueueTransport: tcp
  scheduleQueueAddress: schedule
  scheduleQueueUser: artemis
  scheduleQueuePassword: artemis
  paymentQueueAddress: payment
  paymentQueueUser: artemis
  paymentQueuePassword: artemis
  command: ["/bin/sh","-c"]
  args: ["npm --no-update-notifier run migrate; node index"]
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1

readinessProbe:
  path: /healthy
  port: 3004
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
