{{- define "ffc-demo-payment-service.container" -}}
name: {{ quote .Values.name }}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: POSTGRES_USERNAME
  value: {{ quote .Values.postgresService.postgresUsername }}
- name: POSTGRES_PASSWORD
  value: {{ quote .Values.postgresService.postgresPassword }}
- name: POSTGRES_DB
  value: {{ quote .Values.postgresService.postgresDatabase }}
- name: POSTGRES_HOST
  value: {{ quote .Values.postgresService.postgresExternalName }}
- name: POSTGRES_PORT
  value: {{ quote .Values.postgresService.postgresPort }}
- name: MESSAGE_QUEUE_HOST
  value: {{ quote .Values.container.messageQueueHost }}
- name: MESSAGE_QUEUE_RECONNECT_LIMIT
  value: {{ quote .Values.container.messageQueueReconnectLimit }}
- name: MESSAGE_QUEUE_PORT
  value: {{ quote .Values.container.messageQueuePort }}
- name: MESSAGE_QUEUE_TRANSPORT
  value: {{ quote .Values.container.messageQueueTransport }}
- name: SCHEDULE_QUEUE_ADDRESS
  value: {{ quote .Values.container.scheduleQueueAddress }}
- name: SCHEDULE_QUEUE_USER
  value: {{ quote .Values.container.scheduleQueueUser }}
- name: SCHEDULE_QUEUE_PASSWORD
  value: {{ quote .Values.container.scheduleQueuePassword }}
- name: PAYMENT_QUEUE_ADDRESS
  value: {{ quote .Values.container.paymentQueueAddress }}
- name: PAYMENT_QUEUE_USER
  value: {{ quote .Values.container.paymentQueueUser }}
- name: PAYMENT_QUEUE_PASSWORD
  value: {{ quote .Values.container.paymentQueuePassword }}
 
- name: OIDC_PROVIDER
  value: {{ quote .Values.oidcProvider }}
{{- if .Values.okta }}
- name: OKTA_DOMAIN
  value: {{ quote .Values.okta.domain }}
- name: OKTA_CLIENT_ID
  value: {{ quote .Values.okta.clientId }}
- name: OKTA_AUTH_SERVER_ID
  value: {{ quote .Values.okta.authorizationServerId }}
{{- end }}
{{- if .Values.b2c }}
- name: B2C_CLIENT_ID
  value: {{ quote .Values.b2c.clientId }}
- name: B2C_CLIENT_SECRET
  value: {{ quote .Values.b2c.clientSecret }}
- name: B2C_URL
  value: {{ quote .Values.b2c.url }}
{{- end }}
- name: PORT
  value: {{ quote .Values.container.port }}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
{{- end -}}
