{{- define "ffc-demo-payment-service.container" -}}
name: {{ quote .Values.name }}
envFrom:
- configMapRef:
  name: {{ .Values.name }}-configmap
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: SCHEDULE_QUEUE_NAME
  value: {{ quote .Values.container.scheduleQueueName }}
- name: SCHEDULE_ENDPOINT
  value: {{ quote .Values.container.scheduleQueueEndpoint }}
- name: SCHEDULE_QUEUE_REGION
  value: {{ quote .Values.container.scheduleQueueRegion }}
- name: CREATE_SCHEDULE_QUEUE
  value: {{ quote .Values.container.scheduleCreateQueue }}
- name: PAYMENT_QUEUE_NAME
  value: {{ quote .Values.container.paymentQueueName }}
- name: PAYMENT_ENDPOINT
  value: {{ quote .Values.container.paymentQueueEndpoint }}
- name: PAYMENT_QUEUE_REGION
  value: {{ quote .Values.container.paymentQueueRegion }}
- name: CREATE_PAYMENT_QUEUE
  value: {{ quote .Values.container.paymentCreateQueue }}
- name: OKTA_DOMAIN
  value: {{ quote .Values.okta.domain }}
- name: OKTA_CLIENT_ID
  value: {{ quote .Values.okta.clientId }}
- name: OKTA_AUTH_SERVER_ID
  value: {{ quote .Values.okta.authorizationServerId }}
- name: PORT
  value: {{ quote .Values.container.port }}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
{{- end -}}
