{{- define "ffc-demo-payment-service.container" -}}
name: {{ quote .Values.name }}
volumeMounts:
- name: test-volume
  mountPath: /home/node/config
- name: secret-volume
  mountPath: /home/node/secret
envFrom:
- secretRef:
    name: {{ .Values.name }}-secret
- configMapRef:
    name: {{ .Values.name }}-configmap
env:

- name: CREATE_PAYMENT_QUEUE
  value: {{ quote .Values.container.paymentCreateQueue }}
- name: OKTA_DOMAIN
  value: {{ quote .Values.okta.domain }}
- name: OKTA_CLIENT_ID
  value: {{ quote .Values.okta.clientId }}
- name: OKTA_AUTH_SERVER_ID
  value: {{ quote .Values.okta.authorizationServerId }}
- name: PORT
  value: {{ quote .Values.container.port }}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
{{- end -}}
