{{- define "ffc-demo-payment-service.container" -}}
name: {{ quote .Values.name }}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: POSTGRES_USERNAME
  value: {{ quote .Values.postgresUsername }}
- name: POSTGRES_PASSWORD
  value: {{ quote .Values.postgresPassword }}
- name: POSTGRES_DB
  value: {{ quote .Values.postgresDatabase }}
- name: POSTGRES_HOST
  value: {{ quote .Values.postgresExternalName }}
- name: POSTGRES_PORT
  value: {{ quote .Values.postgresPort }}
- name: SCHEDULE_QUEUE_NAME
  value: {{ quote .Values.container.scheduleQueueName }}
- name: SCHEDULE_ENDPOINT
  value: {{ quote .Values.container.scheduleQueueEndpoint }}
- name: SCHEDULE_QUEUE_REGION
  value: {{ quote .Values.container.scheduleQueueRegion }}
- name: CREATE_SCHEDULE_QUEUE
  value: {{ quote .Values.container.scheduleCreateQueue }}
- name: PAYMENT_QUEUE_NAME
  value: {{ quote .Values.container.paymentQueueName }}
- name: PAYMENT_ENDPOINT
  value: {{ quote .Values.container.paymentQueueEndpoint }}
- name: PAYMENT_QUEUE_REGION
  value: {{ quote .Values.container.paymentQueueRegion }}
- name: CREATE_PAYMENT_QUEUE
  value: {{ quote .Values.container.paymentCreateQueue }}
- name: PORT
  value: {{ quote .Values.container.port }}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe:
  httpGet:
    path: {{ quote .Values.livenessProbe.path }}
    port: {{ .Values.livenessProbe.port }}
  initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
readinessProbe:
  httpGet:
    path: {{ quote .Values.readinessProbe.path }}
    port: {{ .Values.readinessProbe.port }}
  initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
  failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
{{- end -}}
