apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDatabase }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresExternalName }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
