{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service.container-secret") -}}
{{- define "ffc-demo-payment-service.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- if .Values.b2c.url }}
  B2C_CLIENT_ID: {{ .Values.b2c.clientId | quote }}
  B2C_CLIENT_SECRET: {{ .Values.b2c.clientSecret | quote }}
  {{- end }}
  {{- if .Values.okta.domain }}
  OKTA_AUTH_SERVER_ID: {{ .Values.okta.authorizationServerId | quote }}
  OKTA_CLIENT_ID: {{ .Values.okta.clientId | quote }}
  {{- end }}
  POSTGRES_PASSWORD: {{ .Values.postgresService.postgresPassword | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
