{{- template "ffc-helm-library.deployment" (list . "ffc-demo-payment-service.deployment") -}}
{{- define "ffc-demo-payment-service.deployment" -}}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ quote .Values.name }}
      app: {{ quote .Values.namespace }}
  template:
    metadata:
      namespace: {{ .Values.namespace}}
      labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 6 }}
      annotations:
        redeployOnChange: {{ quote .Values.container.redeployOnChange }}
    spec:
      priorityClassName: {{ quote .Values.container.priorityClassName }}
{{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ quote .Values.serviceAccount.name }}
{{- end }}
      restartPolicy: {{ quote .Values.container.restartPolicy }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ quote .Values.imagePullSecret }}
      {{- end }}
      containers:
      - {{ template "ffc-helm-library.container" (list . "ffc-demo-payment-service.container") }}
{{- end -}}
