apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ quote .Values.name }}
  namespace: {{ .Values.namespace}}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ quote .Values.name }}
      app: {{ quote .Values.namespace }}
  template:
    metadata:
      namespace: {{ .Values.namespace}}
      labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 6 }}
      annotations:
        redeployOnChange: {{ quote .Values.container.redeployOnChange }}
    spec:
      priorityClassName: {{ quote .Values.container.priorityClassName }}
{{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ quote .Values.serviceAccount.name }}
{{- end }}
      restartPolicy: {{ quote .Values.container.restartPolicy }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ quote .Values.imagePullSecret }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.container.runAsUser }}
        runAsUser: {{ .Values.container.runAsUser }}
        runAsNonRoot: {{ .Values.container.runAsNonRoot }}        
      containers:
      - name: {{ quote .Values.name }}
        image: {{ quote .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
        command:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
        args:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ quote .Values.container.imagePullPolicy }}        
        securityContext:
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        env:
        - name: NODE_ENV
          value: {{ quote .Values.environment }}
        - name: POSTGRES_USERNAME
          value: {{ quote .Values.postgresUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ quote .Values.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ quote .Values.postgresDatabase }}
        - name: POSTGRES_HOST
          value: {{ quote .Values.postgresExternalName }}
        - name: POSTGRES_PORT
          value: {{ quote .Values.postgresPort }}
        - name: SCHEDULE_QUEUE_NAME
          value: {{ quote .Values.container.scheduleQueueName }}
        - name: SCHEDULE_ENDPOINT
          value: {{ quote .Values.container.scheduleQueueEndpoint }}
        - name: SCHEDULE_QUEUE_REGION
          value: {{ quote .Values.container.scheduleQueueRegion }}
        - name: CREATE_SCHEDULE_QUEUE
          value: {{ quote .Values.container.scheduleCreateQueue }}
        - name: PAYMENT_QUEUE_NAME
          value: {{ quote .Values.container.paymentQueueName }}
        - name: PAYMENT_ENDPOINT
          value: {{ quote .Values.container.paymentQueueEndpoint }}
        - name: PAYMENT_QUEUE_REGION
          value: {{ quote .Values.container.paymentQueueRegion }}
        - name: CREATE_PAYMENT_QUEUE
          value: {{ quote .Values.container.paymentCreateQueue }}
        - name: PORT
          value: {{ quote .Values.container.port }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
          protocol: TCP
        resources:
          requests:
            memory: {{ quote .Values.container.requestMemory }}
            cpu: {{ quote .Values.container.requestCpu }}
          limits:
            memory: {{ quote .Values.container.limitMemory }}
            cpu: {{ quote .Values.container.limitCpu }}
        livenessProbe:
          httpGet:
            path: {{ quote .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ quote .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
