{{- include "ffc-helm-library.deployment" (list . "ffc-demo-payment-service.deployment") -}}
{{- define "ffc-demo-payment-service.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-payment-service.container") }}
      volumes:
      - name: test-volume
        configMap:
          name: {{ .Values.name }}-configmap2
      - name: secret-volume
        secret:
          name: {{ .Values.name }}-secret2
{{- end -}}
