{{- include "ffc-helm-library.deployment" (list . "ffc-demo-payment-service.deployment") -}}
{{- define "ffc-demo-payment-service.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ template "ffc-helm-library.container" (list . "ffc-demo-calculation-service.container") }}
{{- end -}}
