{{- if .Values.postgresExternalName }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.postgresHost }}
  labels:
    environment: {{ quote .Values.environment }}
    app: {{ quote .Values.namespace }}
    app.kubernetes.io/name: {{ quote .Values.name }}
    app.kubernetes.io/instance: {{ quote .Values.labels.instance }}
    app.kubernetes.io/version: {{ quote .Values.labels.version }}
    app.kubernetes.io/component: {{ quote .Values.labels.component }}
    app.kubernetes.io/part-of: {{ quote .Values.namespace }}
    app.kubernetes.io/managed-by: {{ quote .Values.labels.managedBy }}
spec:
  type: ExternalName
  externalName: {{ quote .Values.postgresExternalName }}
  ports:
    - name: port
      port: {{ .Values.postgresPort }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
  namespace: {{ quote .Values.namespace }}
  labels:
    app: {{ quote .Values.namespace }}
    environment: {{ quote .Values.environment }}
    app.kubernetes.io/name: {{ quote .Values.name }}
    app.kubernetes.io/instance: {{ quote .Values.labels.instance }}
    app.kubernetes.io/version: {{ quote .Values.labels.version }}
    app.kubernetes.io/component: {{ quote .Values.labels.component }}
    app.kubernetes.io/part-of: {{ quote .Values.namespace }}
    app.kubernetes.io/managed-by: {{ quote .Values.labels.managedBy }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ quote .Values.namespace }}
    app.kubernetes.io/name: {{ quote .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ quote .Values.service.type }}
