kind: Service
apiVersion: v1
metadata:
  name: mine-support-postgres-payments
  namespace: default
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: port
      port: 5432
---
kind: Service
apiVersion: v1
metadata:
  name: mine-support-message-service
  namespace: default
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: port
      port: 5672
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.component: mine-support-payment-service
  name: mine-support-payment-service
spec:
  ports:
  - name: http
    port: 3004
    targetPort: 3004
  selector:
    app.component: mine-support-payment-service
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: mine-support-payment-service
  name: mine-support-payment-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.component: mine-support-payment-service
    spec:
      containers:   
      - name: mine-support-payment-service
        image: mine-support-payment-service
        imagePullPolicy: Never
        env:                
        - name: NODE_ENV
          value: production
        - name: MINE_SUPPORT_MESSAGE_QUEUE
          value: amqp://mine-support-message-service
        ports:
        - containerPort: 3004              
      restartPolicy: Always
status: {}
