- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3004"   
- key: PAYMENT_TOPIC_ADDRESS
  value: "ffc-demo-payment"
- key: PAYMENT_SUBSCRIPTION_ADDRESS
  value: "payment"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "ffc-demo-schedule" 
- key: SCHEDULE_SUBSCRIPTION_ADDRESS
  value: "payment"  
- key: POSTGRES_DB
  value: "ffc-demo-payment"
- key: POSTGRES_PORT
  value: "5432"  
- key: POSTGRES_SCHEMA_NAME
  value: "public"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"


