- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps1401.postgres.database.azure.com" 
- key: APPINSIGHTS_INSTRUMENTATIONKEY
  value: "36932cc4-12b7-4f0f-bbee-36ba20174390"
- key: POSTGRES_USERNAME
  value: "sndadpinfmid1401-ffc-demo-services" 
- key: EVENT_HOST
  value: ""
- key: EVENT_CLIENT_ID
  value: "" 
- key: EVENT_PORT
  value: ""  
- key: EVENT_MECHANISM
  value: ""  
- key: EVENT_CONSUMER_GROUP_ID
  value: ""
- key: CLAIM_UPDATE_TOPIC_NAME
  value: "" 
- key: CLAIM_UPDATE_TOPIC
  value: ""
- key: CLAIM_UPDATE_FROM_BEGINNING
  value: ""
- key: EVENT_ROUTING_KEY
  value: ""   