- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3004"   
- key: PAYMENT_TOPIC_ADDRESS
  value: "ffc-demo-payment"
- key: PAYMENT_SUBSCRIPTION_ADDRESS
  value: "payment"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "ffc-demo-schedule" 
- key: SCHEDULE_SUBSCRIPTION_ADDRESS
  value: "payment"  
- key: POSTGRES_DB
  value: "ffc-demo-payment"
- key: POSTGRES_PORT
  value: "5432"  
- key: POSTGRES_SCHEMA_NAME
  value: "public"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"
- key: EVENT_CLIENT_ID
  value: "ffc-demo-payment-service" 
- key: EVENT_PORT
  value: "9093"  
- key: EVENT_MECHANISM
  value: "scram-sha-512"  
- key: EVENT_CONSUMER_GROUP_ID
  value: "ffc-demo-payment-service-claim-update"
- key: CLAIM_UPDATE_TOPIC_NAME
  value: "ffc-demo-collector-claim-update" 
- key: CLAIM_UPDATE_TOPIC
  value: "ffc-demo-claim-update-dev"
- key: CLAIM_UPDATE_FROM_BEGINNING
  value: "true"
- key: EVENT_ROUTING_KEY
  value: "" 