- key: MESSAGE_QUEUE_HOST
  value: "PREADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "preadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "preadpinfmi1401-ffc-demo-payment-service"    
- key: EVENT_HOST
  value: "preadpinfen1001"
- key: POSTGRES_DB
  value: "fcp-demo-payment"