- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps3401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "sndadpinfmi3401-ffc-demo-payment-service" 
- key: EVENT_HOST
  value: "sndadpinfen3001"  
- key: POSTGRES_DB
  value: "ffc-demo-payment"