environment: development
postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_payments
postgresHost: mine-support-postgres-payments
postgresExternalName: host.docker.internal
postgresPort: 5432
name: mine-support-payment-service
image: mine-support-payment-service
imagePullSecret:
service:
  type: ClusterIP
  port: 80
container:
  port: 3004
  registry:
  tag: latest
  imagePullPolicy: IfNotPresent
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  redeployOnChange: update this field to force a change
  restartPolicy: Always
  messageQueueHost: amq
  messageQueuePort: "5672"
  messageQueueTransport: tcp
  scheduleQueueAddress: schedule
  scheduleQueueUser: artemis
  scheduleQueuePassword: artemis
  paymentQueueAddress: payment
  paymentQueueUser: artemis
  paymentQueuePassword: artemis
  command: ["/bin/sh","-c"]
  args: ["npm --no-update-notifier run migrate; node index"]  
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1

readinessProbe:
  path: /healthy
  port: 3004
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
